name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0-alpha.3
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: 
    path: ../..
  flutter_html_audio:
    path: ../flutter_html_audio
  flutter_html_iframe:
    path: ../flutter_html_iframe
  flutter_html_math:
    path: ../flutter_html_math
  flutter_html_svg:
    path: ../flutter_html_svg
  flutter_html_table:
    path: ../flutter_html_table
  flutter_html_video:
    path: ../flutter_html_video

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
