name: flutter_html_iframe
description: Iframe widget for flutter_html.
version: 3.0.0-alpha.3
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'

  flutter_html:
    path: ../..

  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
