name: flutter_html_audio
description: Audio widget for flutter_html.
version: 3.0.0-alpha.3
homepage: https://github.com/cerberodev/flutter_html
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html:
    path: ../..

  video_player: '>=2.2.8 <3.0.0'
  chewie_audio: '>=1.3.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: